## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Snaggy's Retreat"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"